version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Install Dependencies 
      - npm config set unsafe-perm true
      - yarn install --frozen-lockfile
      - npm install -g  serverless
  build:
    commands:
      - echo Deploy Next.js
      - npx serverless 
  # post_build:
  #   commands:
  #     - 
  #     - docker push $DOCKER_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG