version: 0.2
env: 
  variables:
    AWS_REGION: "eu-west-1"
    DOCKER_REGISTRY: "376937878789.dkr.ecr.eu-west-1.amazonaws.com"
    IMAGE_REPO_NAME: "dev-rmw-alb"
    IMAGE_TAG: "latest"
    TASK_DEFINITION_CONTAINER_NAME: "dev-rmw-alb-container"
  
phases:
  build:
    commands:
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $DOCKER_REGISTRY/$IMAGE_REPO_NAME
      - echo Building Docker image....
      - docker build --tag $DOCKER_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - echo Push the Docker image to ECR
      - docker push $DOCKER_REGISTRY/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"%s","imageUri":"%s"}]' $TASK_DEFINITION_CONTAINER_NAME  $IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json 
artifacts:
  files:
    - 'image*.json'
    - 'appspec.yaml'
    - 'taskdef.json'
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imagedefinitions.json
